k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: ew11
  currentCluster: arn:aws:eks:eu-west-1:672624372679:cluster/ew11-eks
  clusters:
    arn:aws:eks:eu-west-1:672624372679:cluster/ew11-eks:
      namespace:
        active: ew11sa
        favorites:
        - ew11sa
        - default
      view:
        active: pods
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
