#!/bin/bash

# basic ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'


alias gfr="git pull --rebase"
alias mtr='mtr -t'
alias diff='diff -Naur'
alias df='df -h'
alias youtube-dl='youtube-dl -l'

# safety belt
alias mysql="mysql --safe-updates"

# faster cluster management (use -w to override)
alias dsh='dsh -c -M'
