#!/usr/bin/env bash

# basic ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
if [ "$(uname)" == 'Darwin' ]; then
  alias ls='gls --color'
else
  alias ls='ls --color'
fi
alias gfr="git pull --rebase"
alias mtr='mtr -t'
alias diff='diff -Naur'
alias df='df -h'
alias youtube-dl='youtube-dl -l'

# faster cluster management (use -w to override)
alias dsh='dsh -c -M'

# trim whitespace
function trim {
  awk '{$1=$1};1'
}

# cd to root of git checkout
# shellcheck source=bin/git-wrapper.sh
function git {
  source ~/bin/git-wrapper.sh
}
