#!/bin/bash

# basic ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ls='ls --color'

alias gfr="git pull --rebase"
alias mtr='mtr -t'
alias diff='diff -Naur'
alias df='df -h'
alias youtube-dl='youtube-dl -l'

# faster cluster management (use -w to override)
alias dsh='dsh -c -M'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# trim whitespace
function trim {
  awk '{$1=$1};1'
}
